### ISSUE TITLE
Date Bug

### ISSUE THREAD

**Issue by sigma-us** [johndevedu/flatten-the-curve#1]
Certain Cities must be imssing values and there is no null check in city.helper.js ine 53 and 54
I have a branch ready but get access denied when i try to push to make a PR

**Comment by johndevedu** [comment]
Thanks for the PR! Usually, github PR's happen through a forked repo. 
1) Fork this repo
2) create the fix in that repo (doesn't matter what branch)
3) Submit pr

Let me know if you have further questions!

**Comment by sigma-us** [comment]
Thanks John!
https://github.com/johndevedu/flatten-the-curve/pull/3

**Comment by johndevedu** [comment]
@sigma-us I've actually given you direct access to write to repo now.

Closed by https://github.com/johndevedu/flatten-the-curve/pull/3
